import { Layout } from "@/components/Layout";
import { SeoHead } from "@/components/SeoHead";
import { Card, CardContent } from "@/components/ui/card";
import { Link } from "wouter";
import LastUpdated from "@/components/LastUpdated";

const ACCENT = "#00a884";

export default function Disclaimer() {
  return (
    <Layout>
      <SeoHead
        title="Disclaimer"
        description="Read our disclaimer regarding the use of Invisible Text Generator and our services."
        canonical="https://textsinvisible.com/disclaimer"
        ogTitle="Disclaimer"
        ogDescription="Important disclaimer for using our invisible text tools."
      />
      <div className="max-w-4xl mx-auto py-12 px-1">
        <div className="mb-8 space-y-2">
          <h1 className="text-4xl md:text-5xl font-display font-bold">Disclaimer</h1>
          <LastUpdated page="disclaimer" className="text-muted-foreground" />
        </div>

        <Card className="glass-card overflow-hidden" style={{ borderTop: `4px solid ${ACCENT}` }}>
          <CardContent className="p-8 md:p-10">
            <div className="prose prose-slate max-w-none prose-headings:font-display prose-headings:font-bold prose-p:leading-relaxed prose-a:text-[#00a884] prose-a:no-underline hover:prose-a:underline">
              <p className="text-lg">
                Please read this disclaimer carefully before using the tools and services provided by Textsinvisible.
              </p>

              <h2 className="text-2xl mt-8 mb-4">General Use</h2>
              <p>
                Textsinvisible provides online utility tools designed to generate invisible Unicode characters and specialized text formatting. While we strive to ensure our tools are functional and reliable, all services are provided on an "as-is" and "as-available" basis without any warranties of any kind.
              </p>

              <h2 className="text-2xl mt-8 mb-4">Platform Compatibility</h2>
              <p>
                The effectiveness of invisible text depends on the encoding and rendering rules of third-party platforms (such as WhatsApp, Instagram, Discord, and mobile games). Because these platforms frequently update their software and security protocols, we cannot guarantee that the invisible characters generated here will remain invisible or functional on all apps at all times.
              </p>

              <h2 className="text-2xl mt-8 mb-4">User Responsibility</h2>
              <p>
                You are solely responsible for the way you use the text generated by our website. Textsinvisible does not encourage or condone the use of invisible characters for spamming, harassment, deceptive practices, or any activity that violates the Terms of Service of third-party platforms. Any consequences resulting from the misuse of these characters are the sole responsibility of the user.
              </p>

              <h2 className="text-2xl mt-8 mb-4">No Affiliation</h2>
              <p>
                Textsinvisible is an independent tool provider and is not affiliated, associated, authorized, endorsed by, or in any way officially connected with WhatsApp, Facebook/Meta, Instagram, Discord, Garena Free Fire, or any other platform or game mentioned on this site. All product and company names are trademarks™ or registered® trademarks of their respective holders.
              </p>

              <h2 className="text-2xl mt-8 mb-4">Limitation of Liability</h2>
              <p>
                In no event shall Textsinvisible or its operators be liable for any direct, indirect, incidental, or consequential damages arising out of the use of our tools. Your use of this website is strictly at your own risk.
              </p>

              <div className="not-prose space-y-3 mt-8 sm:mt-12 p-4 sm:p-6 rounded-xl border bg-secondary/10">

                <div className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-2">
                  <span className="font-bold">Website:</span>
                  <a
                    href="https://textsinvisible.com/"
                    className="font-medium underline break-all hover:opacity-80" style={{ color: ACCENT }} target="_blank" rel="noopener noreferrer"
                  > https://textsinvisible.com/
                  </a>
                </div>

                <div className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-2"><span className="font-bold">Contact Page:</span><Link href="/contact" className="font-medium underline break-all hover:opacity-80" style={{ color: ACCENT }} > https://textsinvisible.com/contact/
                </Link>
                </div>

              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </Layout>
  );
}
